# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- 3.10

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true
  clean: true
- script: git submodule update --init --recursive
- task: Gradle@2
  inputs:
    workingDirectory: 'symmetric-assemble'
    options: '-PcheckJava5Compat=true -Dtest.client=h2 -Dtest.server=h2 -Dtest.root=h2 -Dport.number=35507'
    gradleWrapperFile: 'symmetric-assemble/gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
