package org.jumpmind.symmetric.statistic;

public enum StatisticName {
    
    INCOMING_NETWORK_ERRORS,
    INCOMING_DATABASE_ERRORS,
    INCOMING_ROWS_PER_MS,
    INCOMING_BATCH_COUNT,
    INCOMING_ROW_COUNT,
    
    OUTGOING_NETWORK_ERRORS,
    OUTGOING_DATABASE_ERRORS,
    OUTGOING_ROWS_PER_MS,
    OUTGOING_BATCH_COUNT,
    OUTGOING_ROW_COUNT
}
