/**
 * Licensed to JumpMind Inc under one or more contributor
 * license agreements.  See the NOTICE file distributed
 * with this work for additional information regarding
 * copyright ownership.  JumpMind Inc licenses this file
 * to you under the GNU Affero General Public License, version 3.0 (AGPLv3)
 * (the "License"); you may not use this file except in compliance
 * with the License.
 *
 * You should have received a copy of the GNU Affero General Public License,
 * version 3.0 (AGPLv3) along with this library; if not, see
 * <http://www.gnu.org/licenses/>.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.jumpmind.db.platform.db2;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Types;
import java.util.ArrayList;
import java.util.List;

import org.jumpmind.db.alter.AddColumnChange;
import org.jumpmind.db.alter.AddPrimaryKeyChange;
import org.jumpmind.db.alter.ColumnDataTypeChange;
import org.jumpmind.db.alter.CopyColumnValueChange;
import org.jumpmind.db.alter.PrimaryKeyChange;
import org.jumpmind.db.alter.RemoveColumnChange;
import org.jumpmind.db.alter.RemovePrimaryKeyChange;
import org.jumpmind.db.alter.TableChange;
import org.jumpmind.db.model.Column;
import org.jumpmind.db.model.Database;
import org.jumpmind.db.model.ForeignKey;
import org.jumpmind.db.model.ForeignKey.ForeignKeyAction;
import org.jumpmind.db.model.IndexColumn;
import org.jumpmind.db.model.NonUniqueIndex;
import org.jumpmind.db.model.Table;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class Db2DdlBuilderTest {
    private Db2DdlBuilder ddlBuilder;

    @BeforeEach
    void setup() {
        ddlBuilder = new Db2DdlBuilder();
        ddlBuilder.setDelimitedIdentifierModeOn(false);
    }

    @Test
    void testConstructor_configuresDatabaseInfo() {
        assertEquals("SMALLINT", ddlBuilder.getDatabaseInfo().getNativeType(Types.BIT));
        assertEquals("DOUBLE", ddlBuilder.getDatabaseInfo().getNativeType(Types.FLOAT));
        assertEquals("LONG VARCHAR", ddlBuilder.getDatabaseInfo().getNativeType(Types.LONGVARCHAR));
        assertTrue(ddlBuilder.getDatabaseInfo().hasSize(Types.TIMESTAMP));
        assertEquals(254, ddlBuilder.getDatabaseInfo().getDefaultSize(Types.VARCHAR));
        assertEquals(6, ddlBuilder.getDatabaseInfo().getDefaultSize(Types.TIMESTAMP));
        assertEquals(128, ddlBuilder.getDatabaseInfo().getMaxColumnNameLength());
        assertTrue(ddlBuilder.getDatabaseInfo().isNonBlankCharColumnSpacePadded());
        assertTrue(ddlBuilder.getDatabaseInfo().isBlankCharColumnSpacePadded());
        assertFalse(ddlBuilder.getDatabaseInfo().isCharColumnSpaceTrimmed());
        assertFalse(ddlBuilder.getDatabaseInfo().isEmptyStringNulled());
        assertEquals("blob(X'", ddlBuilder.getDatabaseInfo().getBinaryQuoteStart());
        assertEquals("')", ddlBuilder.getDatabaseInfo().getBinaryQuoteEnd());
    }

    @Test
    void testGetNativeDefaultValue_bitColumnTrue_convertsToOne() {
        Column column = new Column("FLAG", false, Types.BIT, 0, 0);
        column.setDefaultValue("true");
        assertEquals("1", ddlBuilder.getNativeDefaultValue(column));
    }

    @Test
    void testGetNativeDefaultValue_bitColumnFalse_convertsToZero() {
        Column column = new Column("FLAG", false, Types.BIT, 0, 0);
        column.setDefaultValue("false");
        assertEquals("0", ddlBuilder.getNativeDefaultValue(column));
    }

    @Test
    void testGetNativeDefaultValue_booleanColumn_convertsUsingSmallintTarget() {
        Column column = new Column("FLAG", false, Types.BOOLEAN, 0, 0);
        column.setDefaultValue("true");
        assertEquals("1", ddlBuilder.getNativeDefaultValue(column));
    }

    @Test
    void testGetNativeDefaultValue_nonBitColumn_fallsBackToSuper() {
        Column column = new Column("NAME", false, Types.VARCHAR, 50, 0);
        column.setDefaultValue("abc");
        assertEquals("abc", ddlBuilder.getNativeDefaultValue(column));
    }

    @Test
    void testWriteColumnAutoIncrementStmt_writesGeneratedByDefaultClause() {
        StringBuilder ddl = new StringBuilder();
        ddlBuilder.writeColumnAutoIncrementStmt(new Table("TEST_TABLE"), new Column("ID"), ddl);
        assertEquals("GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE, ORDER)", ddl.toString());
    }

    @Test
    void testGetSelectLastIdentityValues_returnsIdentityValLocal() {
        assertEquals("VALUES IDENTITY_VAL_LOCAL()", ddlBuilder.getSelectLastIdentityValues(new Table("TEST_TABLE")));
    }

    @Test
    void testWriteExternalIndexDropStmt_writesDropIndexWithoutOnClause() {
        StringBuilder ddl = new StringBuilder();
        NonUniqueIndex index = new NonUniqueIndex("IDX_TEST");
        index.addColumn(new IndexColumn("COL1"));
        ddlBuilder.writeExternalIndexDropStmt(new Table("TEST_TABLE"), index, ddl);
        assertTrue(ddl.toString().startsWith("DROP INDEX IDX_TEST"));
        assertFalse(ddl.toString().contains("ON TEST_TABLE"));
    }

    @Test
    void testWriteCastExpression_sameNativeType_printsIdentifierOnly() {
        StringBuilder ddl = new StringBuilder();
        Column sourceColumn = new Column("COL1", false, Types.INTEGER, 0, 0);
        Column targetColumn = new Column("COL1", false, Types.INTEGER, 0, 0);
        ddlBuilder.writeCastExpression(sourceColumn, targetColumn, ddl);
        assertEquals("COL1", ddl.toString());
    }

    @Test
    void testWriteCastExpression_numericSourceToVarcharTarget_usesCharCast() {
        StringBuilder ddl = new StringBuilder();
        Column sourceColumn = new Column("AMOUNT", false, Types.INTEGER, 0, 0);
        Column targetColumn = new Column("AMOUNT", false, Types.VARCHAR, 50, 0);
        ddlBuilder.writeCastExpression(sourceColumn, targetColumn, ddl);
        assertEquals("CAST(AMOUNT AS CHAR(50))", ddl.toString());
    }

    @Test
    void testWriteCastExpression_differentNonNumericTypes_usesSqlTypeCast() {
        StringBuilder ddl = new StringBuilder();
        Column sourceColumn = new Column("FLAG", false, Types.VARCHAR, 10, 0);
        Column targetColumn = new Column("FLAG", false, Types.INTEGER, 0, 0);
        ddlBuilder.writeCastExpression(sourceColumn, targetColumn, ddl);
        assertTrue(ddl.toString().startsWith("CAST(FLAG AS "));
        assertTrue(ddl.toString().contains("INTEGER"));
    }

    @Test
    void testProcessTableStructureChanges_autoIncrementAddColumn_stopsFurtherProcessing() {
        Table table = new Table("TEST_TABLE", new Column("PK_COL", true, Types.INTEGER, 0, 0));
        Database currentModel = new Database();
        currentModel.addTable(table);
        Column newColumn = new Column("NEW_COL", false, Types.INTEGER, 0, 0);
        newColumn.setAutoIncrement(true);
        List<TableChange> changes = new ArrayList<>();
        changes.add(new AddColumnChange(table, newColumn, null, null));
        changes.add(new RemovePrimaryKeyChange(table, new Column[] { table.getColumn(0) }));
        StringBuilder ddl = new StringBuilder();
        ddlBuilder.processTableStructureChanges(currentModel, currentModel, table, table, changes, ddl);
        assertEquals(0, ddl.length());
        assertEquals(2, changes.size());
    }

    @Test
    void testProcessTableStructureChanges_addAndRemoveColumn_processesAndRemovesRecognizedChanges() {
        Column existingColumn = new Column("OLD_COL", false, Types.INTEGER, 0, 0);
        Table table = new Table("TEST_TABLE", existingColumn);
        Database currentModel = new Database();
        currentModel.addTable(table);
        Column newColumn = new Column("NEW_COL", false, Types.INTEGER, 0, 0);
        List<TableChange> changes = new ArrayList<>();
        changes.add(new AddColumnChange(table, newColumn, null, null));
        changes.add(new RemoveColumnChange(table, existingColumn));
        StringBuilder ddl = new StringBuilder();
        ddlBuilder.processTableStructureChanges(currentModel, currentModel, table, table, changes, ddl);
        assertTrue(changes.isEmpty());
        assertTrue(ddl.toString().contains("ADD COLUMN"));
        assertTrue(ddl.toString().contains("NEW_COL"));
        assertTrue(ddl.toString().contains("DROP COLUMN"));
        assertTrue(ddl.toString().contains("OLD_COL"));
        assertTrue(ddl.toString().contains("REORG TABLE"));
    }

    @Test
    void testProcessTableStructureChanges_primaryKeyChangesAndCopyColumn_processesAndRemovesRecognizedChanges() {
        Column oldPk = new Column("OLD_PK", true, Types.INTEGER, 0, 0);
        Column newPk = new Column("NEW_PK", false, Types.INTEGER, 0, 0);
        Column sourceCol = new Column("SRC_COL", false, Types.INTEGER, 0, 0);
        Column targetCol = new Column("TGT_COL", false, Types.INTEGER, 0, 0);
        Table table = new Table("TEST_TABLE", oldPk, newPk, sourceCol, targetCol);
        Database currentModel = new Database();
        currentModel.addTable(table);
        List<TableChange> changes = new ArrayList<>();
        changes.add(new RemovePrimaryKeyChange(table, new Column[] { oldPk }));
        changes.add(new CopyColumnValueChange(table, sourceCol, targetCol));
        changes.add(new AddPrimaryKeyChange(table, new Column[] { newPk }));
        StringBuilder ddl = new StringBuilder();
        ddlBuilder.processTableStructureChanges(currentModel, currentModel, table, table, changes, ddl);
        assertTrue(changes.isEmpty());
        assertTrue(ddl.toString().contains("DROP PRIMARY KEY"));
        assertTrue(ddl.toString().contains("UPDATE"));
        assertTrue(ddl.toString().contains("TGT_COL=SRC_COL"));
        assertTrue(ddl.toString().contains("ADD CONSTRAINT"));
    }

    @Test
    void testWriteAlterColumnDataTypeToBigInt_nonPrimaryKeyColumn_writesAlterAndReturnsTrue() {
        Column column = new Column("AMOUNT", false, Types.INTEGER, 0, 0);
        Table table = new Table("TEST_TABLE", column);
        ColumnDataTypeChange change = new ColumnDataTypeChange(table, column, Types.BIGINT);
        StringBuilder ddl = new StringBuilder();
        boolean result = ddlBuilder.writeAlterColumnDataTypeToBigInt(change, ddl);
        assertTrue(result);
        assertTrue(ddl.toString().contains("ALTER COLUMN"));
        assertTrue(ddl.toString().contains("SET DATA TYPE"));
    }

    @Test
    void testWriteAlterColumnDataTypeToBigInt_primaryKeyColumn_returnsFalse() {
        Column column = new Column("ID", true, Types.INTEGER, 0, 0);
        Table table = new Table("TEST_TABLE", column);
        ColumnDataTypeChange change = new ColumnDataTypeChange(table, column, Types.BIGINT);
        StringBuilder ddl = new StringBuilder();
        boolean result = ddlBuilder.writeAlterColumnDataTypeToBigInt(change, ddl);
        assertFalse(result);
        assertEquals(0, ddl.length());
    }

    @Test
    void testProcessChange_addColumnChange_writesAddColumnStatement() {
        Table table = new Table("TEST_TABLE", new Column("ID", true, Types.INTEGER, 0, 0));
        Database currentModel = new Database();
        currentModel.addTable(table);
        Column newColumn = new Column("NEW_COL", false, Types.INTEGER, 0, 0);
        AddColumnChange change = new AddColumnChange(table, newColumn, null, null);
        StringBuilder ddl = new StringBuilder();
        ddlBuilder.processChange(currentModel, currentModel, change, ddl);
        assertTrue(ddl.toString().contains("ALTER TABLE"));
        assertTrue(ddl.toString().contains("ADD COLUMN"));
        assertTrue(ddl.toString().contains("NEW_COL"));
        assertNotNull(table.getColumnWithName("NEW_COL"));
    }

    @Test
    void testProcessChange_removeColumnChange_writesDropColumnAndReorgStatements() {
        Column column = new Column("OLD_COL", false, Types.INTEGER, 0, 0);
        Table table = new Table("TEST_TABLE", column);
        Database currentModel = new Database();
        currentModel.addTable(table);
        RemoveColumnChange change = new RemoveColumnChange(table, column);
        StringBuilder ddl = new StringBuilder();
        ddlBuilder.processChange(currentModel, currentModel, change, ddl);
        assertTrue(ddl.toString().contains("DROP COLUMN"));
        assertTrue(ddl.toString().contains("OLD_COL"));
        assertTrue(ddl.toString().contains("CALL SYSPROC.ADMIN_CMD('REORG TABLE"));
        assertNull(table.getColumnWithName("OLD_COL"));
    }

    @Test
    void testProcessChange_removePrimaryKeyChange_writesDropPrimaryKeyStatement() {
        Column pkColumn = new Column("ID", true, Types.INTEGER, 0, 0);
        Table table = new Table("TEST_TABLE", pkColumn);
        Database currentModel = new Database();
        currentModel.addTable(table);
        RemovePrimaryKeyChange change = new RemovePrimaryKeyChange(table, new Column[] { pkColumn });
        StringBuilder ddl = new StringBuilder();
        ddlBuilder.processChange(currentModel, currentModel, change, ddl);
        assertTrue(ddl.toString().contains("DROP PRIMARY KEY"));
        assertFalse(pkColumn.isPrimaryKey());
    }

    @Test
    void testProcessChange_primaryKeyChange_writesDropAndAddPrimaryKeyStatements() {
        Column oldPk = new Column("OLD_PK", true, Types.INTEGER, 0, 0);
        Column newPk = new Column("NEW_PK", false, Types.INTEGER, 0, 0);
        Table table = new Table("TEST_TABLE", oldPk, newPk);
        Database currentModel = new Database();
        currentModel.addTable(table);
        PrimaryKeyChange change = new PrimaryKeyChange(table, new Column[] { oldPk }, new Column[] { newPk });
        StringBuilder ddl = new StringBuilder();
        ddlBuilder.processChange(currentModel, currentModel, change, ddl);
        assertTrue(ddl.toString().contains("DROP PRIMARY KEY"));
        assertTrue(ddl.toString().contains("ADD CONSTRAINT"));
        assertTrue(ddl.toString().contains("CALL SYSPROC.ADMIN_CMD('REORG TABLE"));
        assertFalse(oldPk.isPrimaryKey());
        assertTrue(newPk.isPrimaryKey());
    }

    @Test
    void testWriteExternalPrimaryKeysCreateStmt_appendsReorgStatement() {
        Column pkColumn = new Column("ID", true, Types.INTEGER, 0, 0);
        Table table = new Table("TEST_TABLE", pkColumn);
        StringBuilder ddl = new StringBuilder();
        ddlBuilder.writeExternalPrimaryKeysCreateStmt(table, new Column[] { pkColumn }, ddl);
        assertTrue(ddl.toString().contains("ADD CONSTRAINT"));
        assertTrue(ddl.toString().contains("CALL SYSPROC.ADMIN_CMD('REORG TABLE TEST_TABLE')"));
    }

    @Test
    void testWriteReorgStmt_writesAdminCmdReorgCall() {
        StringBuilder ddl = new StringBuilder();
        ddlBuilder.writeReorgStmt(new Table("TEST_TABLE"), ddl);
        assertEquals("CALL SYSPROC.ADMIN_CMD('REORG TABLE TEST_TABLE')", ddl.toString());
    }

    @Test
    void testWriteCascadeAttributesForForeignKeyUpdate_restrictAction_writesNothing() {
        StringBuilder ddl = new StringBuilder();
        ForeignKey key = new ForeignKey();
        key.setOnUpdateAction(ForeignKeyAction.RESTRICT);
        ddlBuilder.writeCascadeAttributesForForeignKeyUpdate(key, ddl);
        assertEquals(0, ddl.length());
    }

    @Test
    void testWriteCascadeAttributesForForeignKeyUpdate_unsupportedAction_writesNothing() {
        StringBuilder ddl = new StringBuilder();
        ForeignKey key = new ForeignKey();
        key.setOnUpdateAction(ForeignKeyAction.CASCADE);
        ddlBuilder.writeCascadeAttributesForForeignKeyUpdate(key, ddl);
        assertEquals(0, ddl.length());
    }

    @Test
    void testMapDefaultValue_currentTimestampFunction_convertsToPrecisionSix() {
        Column column = new Column("CREATED", false, Types.TIMESTAMP, 0, 0);
        assertEquals("current_timestamp(6)", ddlBuilder.mapDefaultValue("current_timestamp()", column));
    }

    @Test
    void testMapDefaultValue_otherValue_passesThrough() {
        Column column = new Column("NAME", false, Types.VARCHAR, 50, 0);
        assertEquals("abc", ddlBuilder.mapDefaultValue("abc", column));
    }

    @Test
    void testMapDefaultValue_nullValue_returnsNullLiteral() {
        Column column = new Column("NAME", false, Types.VARCHAR, 50, 0);
        assertEquals("NULL", ddlBuilder.mapDefaultValue(null, column));
    }

    @Test
    void testWriteColumnType_singleAutoUpdateTimestampColumn_writesRowChangeClause() {
        Column column = new Column("LAST_UPDATE", false, Types.TIMESTAMP, 0, 0);
        column.setAutoUpdate(true);
        Table table = new Table("TEST_TABLE", column);
        StringBuilder ddl = new StringBuilder();
        ddlBuilder.writeColumnType(table, column, ddl);
        assertEquals("generated by default for each row on update as row change timestamp not null", ddl.toString());
    }

    @Test
    void testWriteColumnType_nonTimestampColumn_fallsBackToSuper() {
        Column column = new Column("AMOUNT", false, Types.INTEGER, 0, 0);
        Table table = new Table("TEST_TABLE", column);
        StringBuilder ddl = new StringBuilder();
        ddlBuilder.writeColumnType(table, column, ddl);
        assertTrue(ddl.toString().contains("INTEGER"));
        assertFalse(ddl.toString().contains("row change timestamp"));
    }

    @Test
    void testWriteColumnType_multipleAutoUpdateTimestampColumns_onlyFirstGetsRowChangeClause() {
        Column first = new Column("FIRST_UPDATE", false, Types.TIMESTAMP, 0, 0);
        first.setAutoUpdate(true);
        Column second = new Column("SECOND_UPDATE", false, Types.TIMESTAMP, 0, 0);
        second.setAutoUpdate(true);
        Table table = new Table("TEST_TABLE", first, second);
        StringBuilder ddl = new StringBuilder();
        ddlBuilder.writeColumnType(table, second, ddl);
        assertFalse(ddl.toString().contains("row change timestamp"));
        assertTrue(ddl.toString().contains("TIMESTAMP"));
    }

    @Test
    void testWriteColumnDefaultValue_timestampAutoUpdateColumn_writesNoDefault() {
        Column column = new Column("LAST_UPDATE", false, Types.TIMESTAMP, 0, 0);
        column.setAutoUpdate(true);
        column.setDefaultValue("current_timestamp()");
        Table table = new Table("TEST_TABLE", column);
        StringBuilder ddl = new StringBuilder();
        ddlBuilder.writeColumnDefaultValue(table, column, ddl);
        assertEquals(0, ddl.length());
    }

    @Test
    void testWriteColumnDefaultValue_normalColumn_writesDefaultValue() {
        Column column = new Column("NAME", false, Types.VARCHAR, 50, 0);
        column.setDefaultValue("abc");
        Table table = new Table("TEST_TABLE", column);
        StringBuilder ddl = new StringBuilder();
        ddlBuilder.writeColumnDefaultValue(table, column, ddl);
        assertTrue(ddl.toString().contains("abc"));
    }
}
