/**
 * Licensed to JumpMind Inc under one or more contributor
 * license agreements.  See the NOTICE file distributed
 * with this work for additional information regarding
 * copyright ownership.  JumpMind Inc licenses this file
 * to you under the GNU Affero General Public License, version 3.0 (AGPLv3)
 * (the "License"); you may not use this file except in compliance
 * with the License.
 *
 * You should have received a copy of the GNU Affero General Public License,
 * version 3.0 (AGPLv3) along with this library; if not, see
 * <http://www.gnu.org/licenses/>.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.jumpmind.db.platform.voltdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;

import java.sql.SQLException;
import java.util.HashMap;

import org.jumpmind.db.model.Column;
import org.jumpmind.db.model.ForeignKey;
import org.jumpmind.db.model.ForeignKey.ForeignKeyAction;
import org.jumpmind.db.model.IIndex;
import org.jumpmind.db.model.IndexColumn;
import org.jumpmind.db.model.NonUniqueIndex;
import org.jumpmind.db.model.Table;
import org.jumpmind.db.model.UniqueIndex;
import org.jumpmind.db.platform.IDatabasePlatform;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class VoltDbDdlReaderTest {
    private VoltDbDdlReader ddlReader;

    @BeforeEach
    void setUp() {
        ddlReader = new VoltDbDdlReader(mock(IDatabasePlatform.class));
    }

    @Test
    void testConstructor_clearsDefaultPatterns() {
        assertNull(ddlReader.getDefaultCatalogPattern());
        assertNull(ddlReader.getDefaultSchemaPattern());
        assertNull(ddlReader.getDefaultTablePattern());
    }

    @Test
    void testIsInternalPrimaryKeyIndex() throws SQLException {
        assertTrue(ddlReader.isInternalPrimaryKeyIndex(null, null, new Table("item"), new NonUniqueIndex("idx")));
    }

    @Test
    void testRemoveSystemIndices_removesAutogeneratedIndices() throws SQLException {
        Table table = new Table("item", new Column("item_id", true));
        table.addIndex(newIndex(new NonUniqueIndex(VoltDbDdlReader.VOLT_DB_SYSTEM_INDEX_PREFIX + "ITEM"), "item_id"));
        ddlReader.removeSystemIndices(null, null, table);
        assertEquals(0, table.getIndexCount());
    }

    @Test
    void testRemoveSystemIndices_keepsUserDefinedIndices() throws SQLException {
        Table table = new Table("item", new Column("item_id", true), new Column("name"));
        table.addIndex(newIndex(new NonUniqueIndex("idx_item_name"), "name"));
        ddlReader.removeSystemIndices(null, null, table);
        assertEquals(1, table.getIndexCount());
        assertEquals("idx_item_name", table.getIndex(0).getName());
    }

    @Test
    void testRemoveSystemIndices_removesTheInternalPrimaryKeyIndex() throws SQLException {
        Table table = new Table("item", new Column("item_id", true));
        table.addIndex(newIndex(new UniqueIndex("pk_item"), "item_id"));
        ddlReader.removeSystemIndices(null, null, table);
        assertEquals(0, table.getIndexCount());
    }

    @Test
    void testDisableAutoIncrement() {
        Column column = new Column("item_id", true);
        column.setAutoIncrement(true);
        Table table = new Table("item", column);
        ddlReader.disableAutoIncrement(table);
        assertFalse(table.getColumn(0).isAutoIncrement());
    }

    @Test
    void testFixIndexKeyOrder_leavesTheRelationAlone() {
        Table table = new Table("item", new Column("item_id", true));
        ddlReader.fixIndexKeyOrder(table);
        assertEquals(1, table.getColumnCount());
    }

    @Test
    void testReadForeignKeyUpdateRule_isAlwaysNoAction() {
        ForeignKey foreignKey = new ForeignKey("fk_item");
        ddlReader.readForeignKeyUpdateRule(new HashMap<String, Object>(), foreignKey);
        assertEquals(ForeignKeyAction.NOACTION, foreignKey.getOnUpdateAction());
    }

    @Test
    void testReadForeignKeyDeleteRule_isAlwaysNoAction() {
        ForeignKey foreignKey = new ForeignKey("fk_item");
        ddlReader.readForeignKeyDeleteRule(new HashMap<String, Object>(), foreignKey);
        assertEquals(ForeignKeyAction.NOACTION, foreignKey.getOnDeleteAction());
    }

    private IIndex newIndex(IIndex index, String columnName) {
        index.addColumn(new IndexColumn(columnName));
        return index;
    }
}
