package org.jumpmind.symmetric.model;

public enum GlobalParameter {
    EVENT_WATCH_POLL_INTERVAL, DATABASE_VERSION, COMPRESS_CONTENT, MAX_EVENTS_TO_SEND, DOWNLOAD_RATE, AUTO_CREATE_TRIGGERS, SYNC_TABLES_PREFIX, EVENT_WATCHER_THREAD_NUMBER;
}
