drop SEQUENCE SEQ_SYM_DATA_DATA_ID;
drop SEQUENCE SEQ_SYM_OUTGOIN_BATCH_BATCH_ID;
drop SEQUENCE SEQ_SYM_OUTGOIN_IST_HISTORY_ID;
drop SEQUENCE SEQ_SYM_TRIGGER_RIGGER_HIST_ID;
#drop SEQUENCE SEQ_TEST_TRIGGERS_TABLE_ID;
