name: Release

on:
    workflow_dispatch:
        inputs:
            version:
                type: string
                description: Full version (major.minor.patch) number to release, e.g. 1.2.3.
                required: true
            latest:
                type: boolean
                description: Whether this release is going to be the latest (major.minor.patch) version.
                required: true
                
run-name: "Release: ${{ inputs.version }}"

jobs:
    create-release:        
        runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-x64
        permissions:
            contents: write

        steps:
            - uses: runs-on/action@v2.1.0
            
            - name: Validate release version input
              shell: bash
              run: |
                echo "Validating release version: ${{ github.event.inputs.version }}"
                if [[ ! "${{ github.event.inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
                    echo "ERROR: Invalid version input. Must be of the format major.minor.patch[.build], e.g. 3.16.6 or 3.16.14.1."
                    exit 1
                fi

            - name: Validate branch
              shell: bash
              run: |
                BRANCH_NAME="${GITHUB_REF##refs/heads/}"
                echo "Validating branch $BRANCH_NAME"
                if [[ "$BRANCH_NAME" != release/* ]]; then
                    echo "ERROR: This workflow only supports a release/* branch."
                    exit 1
                fi
                
            - name: Checkout Source
              uses: actions/checkout@v6.0.2
              with:
                  clean: true
            
            - name: Set up Java
              uses: actions/setup-java@v5.2.0
              with:
                  java-version: 21
                  distribution: 'temurin'
                  cache: gradle

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v6.0.1

            - name: Build with Gradle
              run: |
                ./gradlew clean build
              working-directory: symmetric-assemble
            
            - name: Publish
              run: |
                ./gradlew clean jar releaseSymmetric publishToSonatype publishDocker \
                    -Platest="$LATEST" \
                    -Pversion=${{ github.event.inputs.version }} \
                    -PdeployPassword=${{ secrets.MAVEN_REPO_PASSWORD }} \
                    -PdeployUploadUrl=${{ secrets.MAVEN_REPO_URL }} \
                    -PdeployUser=${{ secrets.MAVEN_REPO_USER }} \
                    -PdockerPassword=${{ secrets.DOCKERHUB_PASSWORD }} \
                    -PdockerUser=${{ secrets.DOCKERHUB_USER }} \
                    -PsourceforgeApiKey=${{ secrets.SOURCEFORGE_API_KEY }} \
                    -PsourceforgePassword=${{ secrets.SOURCEFORGE_PASSWORD }} \
                    -PsourceforgeUser=${{ secrets.SOURCEFORGE_USER }} \
                    -PsonatypeUser=${{ secrets.SONATYPE_USER }} \
                    -PsonatypePassword=${{ secrets.SONATYPE_PASSWORD }}

              working-directory: symmetric-assemble
              env:
                  LATEST: ${{ github.event.inputs.latest }}
                  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_KEY }}
                  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_KEY_PASSWORD }}

            - name: Does Tag Exist?
              id: check_tag_exists
              run: |
                TAG="${{ github.event.inputs.version }}"
                if git ls-remote --tags origin | grep "refs/tags/$TAG$" >/dev/null; then
                    echo "Tag $TAG already exists. Skipping tagging."
                else
                    echo "should_tag=true" >> $GITHUB_OUTPUT
                fi

            - name: Create Tag
              if: steps.check_tag_exists.outputs.should_tag
              id: create_tag
              run: |
                TAG="${{ github.event.inputs.version }}"
                git tag $TAG
                git push origin $TAG
          
                echo "TAG=$TAG" >> $GITHUB_OUTPUT
                
            - name: Create Release in GitHub
              if: steps.check_tag_exists.outputs.should_tag
              uses: softprops/action-gh-release@v2.6.1
              with:
                tag_name: ${{ steps.create_tag.outputs.TAG }}
                name: "Release ${{ steps.create_tag.outputs.TAG }}"
                draft: false
                prerelease: false
