import java.text.SimpleDateFormat;
import java.util.Date;

import org.apache.tools.ant.filters.FixCrLfFilter
import org.apache.tools.ant.filters.ReplaceTokens

configurations {
    sshAntTask
}

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'org.ow2.asm' && !details.requested.name.contains('debug-all')) {
            details.useVersion '9.5'
        }
        if (details.requested.group == 'io.swagger.core.v3') {
            details.useVersion '2.2.30'
        }
    }
}

dependencies {
    sshAntTask 'org.apache.ant:ant-jsch:1.10.15'
}

allprojects {

    apply plugin: 'eclipse'
    apply plugin: 'idea'

    group = 'org.jumpmind.symmetric'
         
    repositories {
        mavenCentral()
        maven { url = "https://maven.vaadin.com/vaadin-addons" }
        maven { url = 'https://plugins.gradle.org/m2' }
        maven { url = "https://packages.confluent.io/maven/" }
        maven { url = "https://repository.mulesoft.org/nexus/content/repositories/public/" }
        maven { url = "https://repo1.maven.org/maven2/" }
    }
        
    ext {
        majorMinorVersion = version.substring(0, version.indexOf(".", version.indexOf(".")+ 1))
    }
    
    sonar {
		properties {
			property "sonar.organization", "jumpmindinc"
		    property "sonar.host.url", "https://sonarcloud.io"
		    property "sonar.projectKey", "jumpmindinc_symmetric-ds"
	        property 'sonar.coverage.jacoco.xmlReportPaths', "${rootDir}/build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml"
	     	property "sonar.coverage.exclusions", "**/*.ad, **/*.js, **/*.c"
	    	property "sonar.scm.disabled", "false"    
		}
	}
}

def ignoreDerivedResources(projectDescription, directories = ["build", "test-output"]) {
  def count = directories.count { file(it).exists() }
  if (count > 0) {
    def filter = projectDescription
      .appendNode("filteredResources")
      .appendNode("filter")
    filter.appendNode("id", System.currentTimeMillis().toString().trim())
    filter.appendNode("type", "26")
    filter.appendNode("name")
    def matcher = filter.appendNode("matcher")
    matcher.appendNode("id", "org.eclipse.ui.ide.orFilterMatcher")
    def arguments = matcher.appendNode("arguments")
    directories.each {
      if (file(it).exists()) {
        def dirMatcher = arguments.appendNode("matcher")
        dirMatcher.appendNode("id", "org.eclipse.ui.ide.multiFilter")
        dirMatcher.appendNode("arguments", "1.0-projectRelativePath-matches-false-false-${it}")
      }
    }
  }
}  

subprojects { subproject ->

    apply plugin: 'java-library'
    apply plugin: 'maven-publish'
    apply plugin: 'jacoco'
    apply plugin: 'signing'    

    jacoco {
		toolVersion = "0.8.12"
	}
    
	jacocoTestReport {
    	def execFiles = fileTree("${project.buildDir}/jacoco").matching {
        	include("*.exec")
    	}.files.findAll { it.exists() }

    	if (!execFiles.isEmpty()) {
        	executionData files(execFiles)
    	}

    	reports {
        	xml.required = true
        	html.required = true
        	xml.outputLocation = file("${buildDir}/reports/jacoco.xml")
        	html.outputLocation = file("${buildDir}/reports/jacoco.html")
    	}
	}

    configurations { deployerJars }
    configurations {
    	testArtifacts.extendsFrom testImplementation
    }

    configurations {
    	provided {
    		canBeResolved = true
        	canBeConsumed = true
        	visible = false
        	transitive = true
        	allDependencies.all {
				dep -> configurations.default.exclude(group: dep.group, module: dep.name)
			}
        }
        api.extendsFrom(provided)
		// Ensure only the compile configuration is exported
		project.idea.module {
			// IDEA internally deals with 4 scopes : COMPILE, TEST, PROVIDED, RUNTIME
			// but only PROVIDED seems to be picked up
			scopes.PROVIDED.plus += [project.configurations.provided]
		}
    }

	java {
		toolchain {
    		languageVersion = JavaLanguageVersion.of(21)
    	}
    	sourceCompatibility=JavaVersion.VERSION_21
    	targetCompatibility=JavaVersion.VERSION_21
    }
    
    compileJava {
    	options.compilerArgs << '-Xlint:deprecation' << '-parameters'
    }
    
    compileTestJava {
    	options.compilerArgs += '-Xlint:deprecation'
    }
	
    
    eclipse {   
        classpath {
            downloadSources = true
            downloadJavadoc = false
	        
	        file {
	        	whenMerged { classpath ->
			        def list = classpath.getEntries()
			        list.removeAll { it.kind=='lib' && it.path.contains('javax.validation') && it.path.contains('validation-api') }
			        classpath.setEntries(list)
			    }
	        }
	        containsTestFixtures = true
        }
        
        jdt {
            sourceCompatibility = JavaVersion.VERSION_21
            targetCompatibility = JavaVersion.VERSION_21
        }
        
        project.file.whenMerged { project ->
            project.natures.remove('org.springsource.ide.eclipse.gradle.core.nature')
            project.natures.remove('org.eclipse.buildship.core.gradleprojectnature')            
        }
    }

    idea {
        module {
            // testResources = []
            testResources.from()
            // testSources = [ file('src/test/java'), file('src/test/groovy')]
            testSources.from(file('src/test/java'))
            testSources.from(file('src/test/groovy'))
            resourceDirs += file('src/test/resources')
            downloadJavadoc = true
            downloadSources = true
        }
    }   
    
    javadoc {
        failOnError = false
    }
    
    afterEvaluate {
        if(plugins.hasPlugin(JavaPlugin)) {
            
            // configuration here
            rootProject.tasks.generateJavadoc {
                source += files(sourceSets.collect { srcSet -> srcSet.allJava })
                classpath += files(sourceSets*.compileClasspath)
            }
    
        }
    }    
    
    publish.enabled = !project.properties.containsKey('pro')
    
    
    task sourcesJar(type: Jar, dependsOn:classes) {
        archiveClassifier = 'sources'
        from sourceSets.main.allSource
    }
    
    artifacts { archives sourcesJar }    
    
    if (!project.name.contains("log-miner") && !project.name.contains("izpack")) {
        publishing {
	    	publications {
	        	symmetricLibrary(MavenPublication) {
	            	from components.java
	        	}
	    	}
	    	repositories {
	        	maven {
	        		name = "jumpmindMaven"
		    		credentials {
		                username = deployUser
		                password = deployPassword
		            }
	            	url = deployUploadUrl
	        	}
	    	}
		}
		
		signing {
			useInMemoryPgpKeys(findProperty("signingKey"), findProperty("signingPassword"))
			sign publishing.publications.symmetricLibrary
		}

        apply plugin: 'eu.kakde.gradle.sonatype-maven-central-publisher'

        def licenseName = project.name.contains("-pro") ? "Commercial" : "GNU AGPL version 3.0";
        sonatypeCentralPublishExtension {
            groupId.set("${project.group}")
            artifactId.set("${project.name}")
            version.set("${project.version}")
            componentType.set("java")
            publishingType.set("AUTOMATIC")
            username.set(getProperty("sonatypeUser"))
            password.set(getProperty("sonatypePassword"))
            pom {
                name.set("${project.name}")
                description.set("Data replication")
                url.set("https://symmetricds.org/")
                licenses {
                    license {
                        name.set(licenseName)
                    }
                }
                developers {
                    developer {
                        name.set("Jumpmind")
                    }
                }
                scm {
                    url.set("https://github.com/jumpmindinc/symmetric-ds/")
                }
            }
        }
    }

    task deploy {
        description = 'Shortcut for Maven users'
        dependsOn tasks.publish
    }

    task testJar(type: Jar) {
        archiveClassifier = "test"
        from sourceSets.test.output
    }
    
    test {
        minHeapSize = "128m"
        maxHeapSize = "512m"
        systemProperty 'sym.keystore.file', "${buildDir}/unittest.keystore"
        useJUnitPlatform {
            excludeTags("integration")
        }
        finalizedBy jacocoTestReport
    }

        
    jar {
        manifest {
            attributes("Implementation-Title": project.name,
                       "Implementation-Version": archiveVersion,
                       "Project-Artifact": project.name,                       
                       "Build-Version": archiveVersion,
                       "Build-Time": new SimpleDateFormat("yyyyMMdd-HHmm").format(new Date()),
                       "Build-Scm-Version": scmVersion)
        }    
    }

    artifacts { testArtifacts testJar }

    ext {
        bshVersion = '2.0b6'
        commonsBeanUtilsVersion = '1.11.0'
        commonsCliVersion = '1.6.0'
        commonsDbcpVersion = '2.13.0'
        commonsFileuploadVersion = '2.0.0-M4'
        commonsIoVersion = '2.19.0'
        commonsLangVersion = '3.18.0'
        commonsTextVersion = '1.12.0'
        commonsCodecVersion = '1.16.1'
        commonsJcsVersion = '3.2.1'
        commonsCollectionVersion = '4.5.0-M3'
        commonsVfs = '2.10.0'
        hamcrestVersion = '1.3'
        hikariVersion = '7.0.2'
        h2Version = '2.4.240'
        derbyVersion = '10.16.1.1'
        postgresqlVersion =  '42.7.13'
        hsqldbVersion = '2.7.0'
        sqliteVersion = '3.45.3.0'
        // Also update mssql-jdbc_auth*.dll (in symmetric-pro:/src/izpack/x64 and x86) and install.xml
        mssqlVersion = '13.4.0.jre11'
        jakartaMailVersion = '2.0.4'
        jdomVersion = '2.0.6.1'
        jaxbVersion = '4.0.5'
        gsonVersion = '2.13.1'
        jacksonVersion = '3.1.3'
        guavaVersion = '33.2.0-android'
        junitVersion = '5.13.3'
        junitPlatformVersion = '1.12.2'
        spotBugsVersion = '4.8.5'
        logbackVersion = '1.5.38'
        slf4jVersion = '2.0.17'
        mockitoVersion = '5.11.0'
        powerMockVersion = '2.0.9'
        mysqlVersion = '8.4.0'
        servletVersion = '4.0.1'
        springVersion = '7.0.9'
        springDataVersion = '4.0.6'
        springBootVersion = '4.1.1'
        jtdsVersion = '1.3.1'
        bouncyCastleVersion = '1.84'
        animalSnifferVersion = '1.23'
        jnaVersion = '5.14.0'
        jettyVersion = '12.1.12'
        websocketVersion = '2.2.0'
        openTelemetryVersion = '1.62.0'
        env = System.getenv()
    }

    dependencies {
        api "ch.qos.logback:logback-classic:$logbackVersion"
        api "ch.qos.logback:logback-core:$logbackVersion"
        api "org.slf4j:slf4j-api:$slf4jVersion"
        api "org.slf4j:jul-to-slf4j:$slf4jVersion"
        api "org.slf4j:jcl-over-slf4j:$slf4jVersion"
        compileOnly "com.github.spotbugs:spotbugs-annotations:$spotBugsVersion"

        testImplementation fileTree(dir: System.getProperty("user.home") + '/.symmetricds/lib', include: '*.jar')
		testImplementation "org.junit.jupiter:junit-jupiter:$junitVersion"
		testRuntimeOnly 'org.junit.platform:junit-platform-launcher:$junitPlatformVersion'
		testRuntimeOnly 'org.junit.platform:junit-platform-engine:$junitPlatformVersion'
        
        testImplementation "org.hamcrest:hamcrest-all:$hamcrestVersion"
        testImplementation "org.mockito:mockito-core:$mockitoVersion"
        testImplementation "org.powermock:powermock-api-mockito2:$powerMockVersion"
        testImplementation "org.powermock:powermock-module-junit4:$powerMockVersion"
        
        deployerJars "org.apache.maven.wagon:wagon-ssh:3.5.3"
    }    

    task develop {
        dependsOn tasks.cleanEclipse, tasks.eclipse, tasks.cleanIdea, tasks.idea, tasks.compileTestJava
        
        doLast {
            def wstFacetXml = "$projectDir/.settings/org.eclipse.wst.common.project.facet.core.xml"
            println "Deleting $wstFacetXml"
            delete wstFacetXml 
        }
    }
}
